package com.jansparta.hvt_project.domain.store.dto

import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.jansparta.hvt_project.domain.store.model.StatNmStatus
import com.jansparta.hvt_project.domain.store.model.Store
import java.time.LocalDateTime

data class StoreResponse constructor(
    @JsonProperty("id") val id: Long,
    @JsonProperty("company") var company: String?,
    @JsonProperty("shopName") var shopName: String?,
    @JsonProperty("domainName") var domainName: String?,
    @JsonProperty("tel") var tel: String?,
    @JsonProperty("email") var email: String?,
    @JsonProperty("upjongNbr") var upjongNbr: String?,
    @JsonProperty("ypForm") var ypForm: String?,
    @JsonProperty("firstHeoDate") var firstHeoDate: String?,
    @JsonProperty("comAddr") var comAddr: String?,
    @JsonProperty("statNm") var statNm: String?,
    @JsonProperty("totRatingPoint") var totRatingPoint: Int?,
    @JsonProperty("chogiRatingPoint") var chogiRatingPoint: Int?,
    @JsonProperty("chungRatingPoint") var chungRatingPoint: Int?,
    @JsonProperty("dealRatingPoint") var dealRatingPoint: Int?,
    @JsonProperty("pyojunRatingPoint") var pyojunRatingPoint: Int?,
    @JsonProperty("securityRatingPoint") var securityRatingPoint: Int?,
    @JsonProperty("service") var service: String?,
    @JsonProperty("chung") var chung: String?,
    @JsonProperty("chogi") var chogi: String?,
    @JsonProperty("gyulje") var gyulje: String?,
    @JsonProperty("pyojun") var pyojun: String?,
    @JsonProperty("pInfoCare") var pInfoCare: String?,
    @JsonProperty("perInfo") var perInfo: String?,
    @JsonProperty("dealCare") var dealCare: String?,
    @JsonProperty("sslYn") var sslYn: String?,
    @JsonProperty("injeung") var injeung: String?,
    @JsonProperty("baesongYejeong") var baesongYejeong: String?,
    @JsonProperty("baesong") var baesong: String?,
    @JsonProperty("clientBbs") var clientBbs: String?,
    @JsonProperty("leave") var leave: String?,
    @JsonProperty("kaesolYear") var kaesolYear: String?,
    @JsonProperty("regDate") var regDate: String?,
    @JsonProperty("createdDate") var createdDate: LocalDateTime?,
    @JsonProperty("modifiedDate") var modifiedDate: LocalDateTime?
)

fun Store.toResponse(): StoreResponse {
    return StoreResponse(
        id = id!!,
        company = company,
        shopName = shopName,
        domainName = domainName,
        tel = tel,
        email = email,
        upjongNbr = upjongNbr,
        ypForm = ypForm,
        firstHeoDate = firstHeoDate,
        comAddr = comAddr,
        statNm = statNm.name,
        totRatingPoint = totRatingPoint,
        chogiRatingPoint = chogiRatingPoint,
        chungRatingPoint = chungRatingPoint,
        dealRatingPoint = dealRatingPoint,
        pyojunRatingPoint = pyojunRatingPoint,
        securityRatingPoint = securityRatingPoint,
        service = service,
        chung = chung,
        chogi = chogi,
        gyulje = gyulje,
        pyojun = pyojun,
        pInfoCare = pInfoCare,
        perInfo = perInfo,
        dealCare = dealCare,
        sslYn = sslYn,
        injeung = injeung,
        baesongYejeong = baesongYejeong,
        baesong = baesong,
        clientBbs = clientBbs,
        leave = leave,
        kaesolYear = kaesolYear,
        regDate = regDate,
        createdDate =createdDate,
        modifiedDate = modifiedDate,
    )
}